### ISSUE TITLE
Zapier + Woovi

### ISSUE THREAD

**Issue by igorfelipeduca** [Open-Pix/zapier-woovi#1]
Planning issues for Zapier + Woovi integration

- [x] Create a map of all N8N + Woovi triggers (Issue #2)
- [x] Create Woovi AppID authorization with Zapier (Issue #3 )
- [ ] Mapping the zapier (Issue #4)
- [ ] Create webhook trigger (Issue #5)
- [ ] Create charge trigger (Issue #6)
